### ISSUE TITLE
First DA1 led bar never lites on

### ISSUE THREAD

**Issue by PicoElements** [RBSC/MSX-EQ#3]
Hello.
I love this project and i succeded in building a board with led bars. Actually i'm trying with a Toshiba HX-20 using King's Valley as a game in the second slot and the MSX-EQ board in the first slot.

Tha strange thing is that only the first  led bar is not working, all the others work. I tested the led orientation and is with negative on the right for each bar. Maybe the game is not using the frequencies at DA1 ? Maybe some bad joint? Can you suggest me a game i could use to be sure the first bar is used?

Thanks a lot for your help,
Stefano

**Comment by Pyhesty** [comment]
Hello!
Thank you very much for your interest.
Check it on demo aytunes or bad apple
https://www.pouet.net/prod.php?which=89905
https://www.pouet.net/prod.php?which=89738
you can see effect:
https://youtu.be/Vhv5bKJgaLk?t=950
Unfortunately, many PLD often have damaged pins. Change PLD
Good luck.
Dmitri 
aka Pyhesty

**Comment by PicoElements** [comment]
Thank you Dmitri for your answer! I will try to build another board or swap the PLD.
I'm using 10 led bar and i've filled the board with 1k resistors also if i noticed that only 8 leds are used. Could it be an issue?
Thnks!

EDIT: finally i made another game, Goonies, i don't have carnivore yet, now i'm waiting a friend that could come to test, but now with this game i can see the first bar moving so , it's the frequency, the board is safe !
Any plan to use all the ten leds? 
Thanks a lot!
